### ISSUE TITLE
Segmentation Fault after compiling binary on my own

### ISSUE THREAD

**Issue by chillmatin** [CallumBeaney/people#1]
I couldn't run it under gdb too to see where the segfault happened.

**Comment by chillmatin** [comment]
after fiddling around with the source code, I came to conclusion that the segmentation fault is due to missing data file. We should somehow implement a method that automatically creates empty data files for it.

**Comment by aprzn123** [comment]
I put together a simple fix for it that was just
```c
if (file == NULL) {
    file = fopen("NAMEFILE", "w+");
}
```
after line 129.

As for gdb, you can just recompile with -g.

**Comment by chillmatin** [comment]
Same issue also persists with timefile. Thank you for taking your time on the fix.

**Comment by CallumBeaney** [comment]
I'm sorry about this; as well as the opening fix, it looks like the program could also segfault as a result of basically executing `fclose(NULL)` at certain points, which is undefined.

This occurs in a few other places, so I will go through it, push a corrected version incorporating the fopen method suggested by aprzn123 where appropriate, and notify you afterwards.

**Comment by CallumBeaney** [comment]
@chillmetin 
Hi Matin, the code has been updated. Environment variables have been implemented by @aprzn123 and all aberrant fclose() instances removed.

**Comment by chillmatin** [comment]
Initial segmentation fault was due to argc == 1 case in which application tried to access argv[1] when argc was 1.

**Comment by chillmatin** [comment]
Pull request is made to fix this issue.
