### ISSUE TITLE
feature: allow TIMEFILE and NAMEFILE as environment variables

### ISSUE THREAD

**Issue by aprzn123** [CallumBeaney/people#2]
The current definitions of TIMEFILE and NAMEFILE being hardcoded at runtime are a pain if users want to update without having to deal with recompiling everything. 

I propose that it instead uses environment variables with names like `PEOPLE_NAMEFILE` and `PEOPLE_TIMEFILE` that the executable reads and uses to determine the file location. I can implement this in a fork, any thoughts or issues with it?

**Comment by CallumBeaney** [comment]
That's a great idea -- thank you & please do go ahead! I will keep an eye on notifications and merge when ready.
